version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - pwd
      - ls -la
      - npm run build
      - aws s3 sync build/ ${BUCKET_NAME}
      - aws cloudfront create-invalidation --distribution-id ${CF_ID} --paths "/*"
